// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCKPbLtKPzK6-GUaPyUxnvGIb0oTem023Q',
//     appId: '1:704154561398:web:86c04cbab9ff2e4ef92857',
//     messagingSenderId: '704154561398',
//     projectId: 'flutter-application-1-3183c',
//     authDomain: 'flutter-application-1-3183c.firebaseapp.com',
//     storageBucket: 'flutter-application-1-3183c.appspot.com',
//     measurementId: 'G-8EETLCJD4G',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDEmNy9tXmlAXiuJBD-m1CYhcJj-EgUYvs',
//     appId: '1:704154561398:android:2f4d1e31fdcba36ff92857',
//     messagingSenderId: '704154561398',
//     projectId: 'flutter-application-1-3183c',
//     storageBucket: 'flutter-application-1-3183c.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDIOKwppVVXJm-KM1dAjXkyTFe73b2fzJ8',
//     appId: '1:704154561398:ios:95c88d3c458805fef92857',
//     messagingSenderId: '704154561398',
//     projectId: 'flutter-application-1-3183c',
//     storageBucket: 'flutter-application-1-3183c.appspot.com',
//     iosBundleId: 'com.tempFlutter.flutterApplication1',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDIOKwppVVXJm-KM1dAjXkyTFe73b2fzJ8',
//     appId: '1:704154561398:ios:95c88d3c458805fef92857',
//     messagingSenderId: '704154561398',
//     projectId: 'flutter-application-1-3183c',
//     storageBucket: 'flutter-application-1-3183c.appspot.com',
//     iosBundleId: 'com.tempFlutter.flutterApplication1',
//   );
// }
